spring:
  profiles:
    active: dev   # Default to 'dev' ? override this in prod
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver  # Override in dev if needed
  data:
    rest:
      base-path: /simplerp/api/
  sql:
    init:
      mode: always
